resource_group_name = "gitops"
location            = "East US 2"                 
app_service_plan_name   = "demo-gitops"
web_app_name            = "demo-prod-web-app"
environment             = "prod"