resource_group_name = "gitops"
location            = "East US 2"                 
app_service_plan_name   = "demo-splan-prod"
web_app_name            = "demo-webapp-prod"
environment             = "prod"