resource_group_name = "gitops"
location            = "East US 2"                 
web_app_name            = "demo-qa-web-app"
app_service_plan_name   = "demo-qa-app-service"
environment             = "qa"